apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: roboshop
  region: us-east-1

managedNodeGroups:
  - name: roboshop-ng
    spot: true
    minSize: 2
    maxSize: 4
    desiredCapacity: 3
    instancesDistribution:
      instanceTypes: ["m5.large", "c3.large", "c4.large", "c5.large"]
      onDemandBaseCapacity: 0
      onDemandPercentageAboveBaseCapacity: 0
      spotInstancePools: 4
    ssh:
      publicKeyName: kubernetes

