apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: roboshop
  region: us-east-1

managedNodeGroups:
  - name: roboshop-ng
    capacityType: SPOT
    instanceTypes: ["m5.large", "c4.large", "c5.large"]
    minSize: 2
    maxSize: 4
    desiredCapacity: 3
    ssh:
      publicKeyName: kubernetes

